<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7FTL27E" failures="1" tests="3" name="Error validation" time="37.969" errors="0" timestamp="2025-02-27T10:21:52 IST">
  <testcase classname="Tests.ErrorValidation_login" name="ErrorValidation_login" time="0.923">
    <skipped/>
  </testcase> <!-- ErrorValidation_login -->
  <testcase classname="Tests.ErrorValidation_login" name="ErrorValidation_login" time="1.267">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Tests.ErrorValidation_login.ErrorValidation_login(ErrorValidation_login.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ErrorValidation_login -->
  <testcase classname="Tests.ErrorValidation_login" name="ProductpageErrorValidation" time="14.649"/>
</testsuite> <!-- Error validation -->
